# SConscript do Castella: constroi baseado no ambiente da raiz (SConstruct)
# coding: utf-8
Import ('env')

# Os arquivos fonte são os .cpp dentro das pastas e a main
src = Glob ('*/*.cpp')
src += ['main.cpp']#, '#include/ContentTable.hpp']

# compila o programa Castella
env.Program ('Castella', src)
